apiVersion: syngit.io/v1beta2
kind: RemoteUser
metadata:
  labels:
    app.kubernetes.io/name: remoteuser
    app.kubernetes.io/instance: remoteuser-sample
    app.kubernetes.io/part-of: syngit
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: syngit
  name: remoteuser-sample
  annotations:
    syngit.io/associated-remoteuserbinding: "true"
    github.syngit.io/auth.test: "true"
spec:
  gitBaseDomainFQDN: github.com
  email: my@email.com
  secretRef:
    name: my-github-personal-access-token-secret

